

# # [INITIAL] Only for debugging----
# path.root <- normalizePath(getwd(),winslash = "\\")
# path.QC <- normalizePath(paste0(path.root,"/QC"),winslash = "\\")
# path.QCtoWrite <- normalizePath(paste0(path.QC,"/Regelkarten"),winslash = "\\")
#
#
#
# _____________________________________________________________________________________________________________
# _____________________________________________________________________________________________________________

# [QC HANDLER] ----
myQC.Defaults.csv <- function(results.list = myList.Converter(myList), # Converts the measurement results in a uniform list
                              df.defaults.QC = read.defaults() %>% # Extract QC default data
                                filter(SAA.Menue %in% myList$Input.Parameter$SAA.Selected) %>% # Info about stored QC-Values defined by QC-Method (e.g. "VBW", "MM2" and "MM3" from "SAA 2.3.1 Pt-Gesamt")
                                select(Analyt,Element,SAA,QC.Kind,QC.Name,QC.RegEx,Filename,Zielwert,Unsicherheit,LimitBG,Unit.Accept,Masse,QC.Spike), # Needed Values
                              QCSoll = myList$Input.Parameter$QC$QCSoll,
                              NonDefaultAnalyt.vec = NULL,
                              path.QCtoWrite = normalizePath(paste0(getwd(),"/QC/Regelkarten")),
                              perform.RegEx = TRUE){
  #__________________________
  # The results.list is a list with converted and uniformed results from myList. It consists of single data.frames separated by different parameters or analytes 
  # This function requires a pre-selection of tracked Analyts.
  # This list can be generated by myList.Converter(myList) function only for default/defined QC.Methods.
  
  # Check if converter is available for this Measurement (only default QC Methods are available) --> myList.Converter()
  if (is.null(results.list)) {
    return(NULL)
  }
  
  #__________________________
  # df.defaults.QC is the data.frame generated by read.default() function. Only the columns 
  # Analyt, SAA, QC.Kind, QC.Name, QC.RegEx, Filename, Zielwert, Unsicherheit, LimitBG, Unit.Accept, Masse
  # are needed for processing.
  
  # Check for a selected defined method
  if (nrow(df.defaults.QC) == 0) {
    return(NULL)
  }
  
  #__________________________
  # QCSoll are Values defined by the User in UI and stored in myParams$QC (myParams is a list with input variables 
  # of UI and is copied in myList$Input.Parameter). This Values are needed for calculation of WFR
  
  # QCSoll must not be specified. It's only available for QC.Kind == "QC"
  # VBW samples are not linked to QCSoll
  
  #__________________________
  # NonDefaultAnalyt.vec is a vector with an identifier for an measured trace. Only one trace per analyte is allowed
  # for extraction of QC values. This vector is only needed if in defaults.csv no Analyt can be specified, because of
  # necessary individuel selection by user (e.g. iTeva measurements)
  
  #__________________________
  # perform.RegEx is TRUE if data extraction from SampleList has to be done (normal execution)
  # FALSE if the extracted QCData from SampleList should not be written/stored in file.
  # This is useful when the delete.QC function will delete the last written point so that the duplication check fails, 
  # because the point from actual loaded file is deleted and the point will be inserted it again.
  #________________________________________________________________
    
  if(!is.null(NonDefaultAnalyt.vec)){
    # The Analyt variable link the user-selected measured trace to the analyte. This is used for selection, if more than one signal trace is available for one Analyte.
    # E.g. eQuant Pt: "194Pt (mp_Std)" and "195Pt (mp_Std)". Two masses are measured the detect Pt. Furthermore, the tuning parameters can be varied for the same mass.
    # E.g. eQuant Pt: "195Pt (mp_Std)" and "195Pt (sa-3V-H2)".  The same mass of Pt was measured with different Collision-Cell settings.
    # In the report and QC control chart only ONE trace can be considered. Therefore, a selection must be made by the column Analyt in defaults.csv
    # Or, as long as this is not possible like in the case of ICP-OES measurements (iTeva), by manuelly defined Analyts in the NonDefaultAnalyt.vec variable.
    
    # This function prioritise the items in the defaults.csv and is searching in the next step the corresponding results in the results.list for tracking in ControlChart.
    # Due to this order, the NonDefaultAnalyt.vec must match the items in the df.defaults.QC dataframe. 
    # Furthermore, the order is fixed and given by df.defaults.QC.
    # This match can be automated by comparing the items in NonDefaultAnalyt.vec with defined Elements.
    # Only in tQuant application this comparison can not be made. In this case a definition of Analyt in defaults.csv is absolutely essential. 
    
    # else (re)define the Analyt column in df.defaults.QC dataframe according the Elements and NonDefaultAnalyt.vec items
    for (i in 1:nrow(df.defaults.QC)) { # loop for items in df.defaults.QC
      
      if (is.na(df.defaults.QC$Analyt[i])) {
        # Exception, if no analyte is defined in default.csv
        # Proof if user selected an analyte by available element corresponding value in NonDefaultAnalyte.vec
        if (any(str_detect(NonDefaultAnalyt.vec,df.defaults.QC$Element[i]))) {
          df.defaults.QC$Analyt[i] <- NonDefaultAnalyt.vec[
            which( # if more than one selection was made for one element, the first match will be selected
              str_detect(NonDefaultAnalyt.vec,df.defaults.QC$Element[i])
              )[1]
            ]
        }
      } else if (length(grep(df.defaults.QC$Element[i],NonDefaultAnalyt.vec,fixed = T))==0) { 
        # exception if no match found: length is 0 if:
        # - in default.csv defined analyte was not measured or selected!
        df.defaults.QC$Analyt[i] <- NA # fill value with NA
      } else {
        # (re)define the Analyt column in df.defaults.QC dataframe when user selected an other analyte (different value in NonDefaultAnalyt.vec)
        df.defaults.QC$Analyt[i] <- NonDefaultAnalyt.vec[NonDefaultAnalyt.vec[str_detect(NonDefaultAnalyt.vec,df.defaults.QC$Element[i])]]
      }
    }
  }
  
  
  # An empty list as storage for looped returns
  QC <- list()
  
  for (i in 1:nrow(df.defaults.QC)) {
    # Go to next QC definition if no QC-File is defined in defaults.csv
    if (is.na(df.defaults.QC$Filename[i])) {
      QC[[df.defaults.QC$QC.Name[i]]] <- NA
      next
    }
    # Path of QC Chart file
    QCpath <- suppressWarnings(normalizePath(paste0(path.QCtoWrite,"/",df.defaults.QC$Filename[i]),winslash = "\\"))
    
    # Extract QC Data from samplelist by reguelar expression defined in defaults.csv
    if (is.na(df.defaults.QC$Analyt[i]) | is.null(df.defaults.QC$Analyt[i])) { # if Paramters are not specified by defaults.csv
      QCData <- data.frame() # generate an empty dataframe (to trigger the next "if condition")
    } else { # else perceed as expected
      
      # Extract all data of desired analyte
      Measured.Data <-  results.list[[grep(pattern = df.defaults.QC$Analyt[i],x = names(results.list),fixed = T)]]#get the data.frame with results of specific analyte
      # Extract only QC data of desired analyte
      QCData <- Measured.Data %>% filter(str_detect(Labels, df.defaults.QC$QC.RegEx[i])) # extract the QC relevant data
      
      # Check if QC.Spike is selected -> Extension of RegEx to extract the original sample
      if (df.defaults.QC$QC.Kind[i] == "QC" && as.logical(df.defaults.QC$QC.Spike[i])) {
        # Info about Spiked samples
        QCData.Conc <- Measured.Data %>% filter(str_detect(Labels, df.defaults.QC$QC.RegEx[i])) %>% select(Labels,Concentration)
        QCData.Conc <- QCData.Conc$Concentration %>% `names<-`(QCData.Conc$Labels)
        
        # Info about Original samples
        QCData.Conc.Orig <- Measured.Data %>% filter(Labels %in% str_extract(names(QCData.Conc),"^M.[[:digit:]]*/[[:digit:]]*")) %>% select(Labels,Concentration) %>% group_by(Labels) %>% summarise_all(mean)
        QCData.Conc.Orig <- QCData.Conc.Orig$Concentration %>% `names<-`(QCData.Conc.Orig$Labels)
      }
      
    }
    
    
    
      # Go to next QC definition if no specified QC Data was measured for this default
    if (nrow(QCData) == 0) { # The number of rows in QCData is zero if e.g. the QC.RegEx couldn't be found, or if no Analyt was defined in defaults.csv
      QCData <- NA
    }else{
      # Get the unique Name of the QC Sample
      whichQC.name <- df.defaults.QC$QC.Name[i] 
      # Get the dominator (which value for QC should have been measured?) <- User-input
      whichQC.soll <- QCSoll %>% filter(QC.Name %in% whichQC.name) %>% select(QC.Norm) %>% as.numeric()
      
      # If QC.Kind is QC, then the WFR must be calculated
      if (df.defaults.QC$QC.Kind[i] == "QC") {
        # Check if QC.Spike is selected -> Extension of RegEx to extract the original sample
        if (as.logical(df.defaults.QC$QC.Spike[i])) {
          # Function to handle diffenrent numbers of conc.Orig and extracted spiked data.
          # E.g. one measured original sample but 5 time repetition of spike or
          # n-time repetition of measurement of original sample but one spiked sample
          
          res <- qc.spike(conc.org = QCData.Conc.Orig,
                          conc.spk = QCData.Conc,
                          conc.def = whichQC.soll)
          
          
          
          QCData <- data.frame(Labels = QCData$Labels,
                               StartTime = QCData$StartTime,
                               Concentration = res$Concentration,
                               WFR = res$WFR,
                               Defined = whichQC.soll,
                               Comment = QCData$Comment,
                               TimeStamp = QCData$TimeStamp,
                               Operator = QCData$Operator,
                               Outlier = QCData$Outlier)
        }else{
          # compute the quotient in %
          QCData$WFR <- as.numeric(QCData$Concentration)/whichQC.soll*100
          # Convert in standard format
          QCData <- data.frame(Labels = QCData$Labels,
                               StartTime = QCData$StartTime,
                               Concentration = QCData$Concentration,
                               WFR = QCData$WFR,
                               Defined = whichQC.soll,
                               Comment = QCData$Comment,
                               TimeStamp = QCData$TimeStamp,
                               Operator = QCData$Operator,
                               Outlier = QCData$Outlier)
        }
      }
      # Format all columns in character
      QCData[, ] <- lapply(QCData[, ], as.character)
      
      if (perform.RegEx) {
        # Write the QC data in a file
        write.qc(QCData,QCpath)
      }
    }
    
    
    # Generate the ControlChart
    #__________________________
    
    # Read the table from file
    # Convert the columns
    # perfomed by read.QC()
    
    # Generate the plot and store as variable
    # Differenz between VBW and QC
    # VBW plots Concentration
    # QC plots WFR
    
    if (file.exists(QCpath)){ # Only evaluated if file exists
      if (df.defaults.QC$QC.Kind[i] == "VBW") {
        
        plot.QC <- myBlindwertkartenPlot(plotData = read.QC(QCpath),
                                         BWKrit = df.defaults.QC$LimitBG[i],
                                         title = paste(df.defaults.QC$QC.Name[i],"Regelkarte"),
                                         yLabel = paste("Konzentration",df.defaults.QC$Unit.Accept[i]),
                                         xLabel = "Messzeitpunkt")
      }else if (df.defaults.QC$QC.Kind[i] == "QC") {
        
        plot.QC <- myZielwertkartenPlot(plotData = read.QC(QCpath),
                                        Zielwert = df.defaults.QC$Zielwert[i],
                                        Unsicherheit = df.defaults.QC$Unsicherheit[i],
                                        title = paste(df.defaults.QC$QC.Name[i],"Regelkarte"),
                                        yLabel = paste("Wiederfindungsrate",df.defaults.QC$Unit.Accept[i]),
                                        xLabel = "Messzeitpunkt")
      }
    
      QC[[df.defaults.QC$QC.Name[i]]] <- list("QC.Data" = QCData,
                                              "QC.defaults" = df.defaults.QC[i,],
                                              "QC.Table" = read.QC(QCpath),
                                              "QC.Plot" = plot.QC)
    }else{
      next
    }
  }
  return(QC)
}

# [CONVERTER] myList.Converter ----
myList.Converter <- function(myList){
  # Function for extraction of relevant evaluated data from myList and return it in one converted data.frame
  
  # Empty list for collection and output of converted file
  data.list <- list()

  if(any(myList$Input.Parameter$System == c("eQuant (MS)","eQuant (OES)"))){  #### [CONVERTER: eQuant] ----
    for (i in 1:length(myList[["Calibration"]][["Info"]][["Analytes"]])) {
      
      # Merge:
      # "Labels","StartTime","Intensity","Concentration"
      
      # Raw concentration must be multiplied with the dilution factor in order to get not BG cleaned values (ONLY USED FOR QC)
      conc <- myList$Concentration$Concentration %>% select(Index,Labels,myList[["Calibration"]][["Info"]][["Analytes"]][i])
      # Multiply with dilution factor, since it is normally done afer filter BG
      conc[myList[["Calibration"]][["Info"]][["Analytes"]][i]] <- conc[myList[["Calibration"]][["Info"]][["Analytes"]][i]] * as.numeric(myList$Header$`Dilution Factor`)
      
      # Merging the data tables
      data <- myList$Header %>% select(Index,Labels,StartTime,Comments) %>% # StartTime is available only in Header
        merge(.,myList$Raw.Data$eQuant$Raw$Raw.Average$Data %>% select(Index,Labels,myList[["Calibration"]][["Info"]][["Analytes"]][i]),by = c("Index","Labels")) %>% # Intensity is available only in Raw
        merge(.,conc,by = c("Index","Labels")) %>%  # Concentration is available only in concentration
        select(-Index) # Index is not relevant anymore, due the StartTime as unique identifier
      
      # Add columns for Comment TimeStamp and Operator for further Comment functions
      data$TimeStamp <- ""
      data$Operator <- ""
      data$Outlier <- "0"
      
      # Rename the columns
      names(data) <- c("Labels","StartTime","Comment","Intensity","Concentration","TimeStamp","Operator","Outlier")
      
      # Convert NA's in Comment column to empty characters
      data$Operator[!is.na(data$Comment)] <- myList$Input.Parameter$Operator
      data$TimeStamp[!is.na(data$Comment)] <- format(Sys.time(),"%Y-%m-%d")
      data$Comment[is.na(data$Comment)] <- ""
      
      # Collection in a list
      data.list[[myList[["Calibration"]][["Info"]][["Analytes"]][i]]] <- data
    }
    
    
  }else if(myList$Input.Parameter$System == "tQuant (MS)"){ # [CONVERTER: tQuant] ----
    
    for (i in 1:length(myList[["Calibration"]][["Info"]][["Analytes"]])) {
      
      # Merge:
      # "Labels","StartTime","Intensity","Concentration"
      
      # Raw concentration must be multiplied with the dilution factor in order to get not BG cleaned values (ONLY USED FOR QC)
      conc <- myList$Concentration$Concentration %>% select(Index,Labels,myList[["Calibration"]][["Info"]][["Analytes"]][i])
      # Multiply with dilution factor, since it is normally done afer filter BG
      conc[myList[["Calibration"]][["Info"]][["Analytes"]][i]] <- conc[myList[["Calibration"]][["Info"]][["Analytes"]][i]] * as.numeric(myList$Header$`Dilution Factor`)
      
      data <- myList$Header %>% select(Index,Labels,StartTime,Comments) %>% # StartTime and Comment is available only in Header
        merge(.,myList$Prepared$Chromatography.PeakArea$Data %>% select(Index,Labels,myList[["Calibration"]][["Info"]][["Analytes"]][i]),by = c("Index","Labels")) %>% # Intensity is available only in Raw
        merge(.,myList$Concentration$Concentration %>% select(Index,Labels,myList[["Calibration"]][["Info"]][["Analytes"]][i]),by = c("Index","Labels")) %>%  # Concentration is available only in concentration
        select(-Index) # Index is not relevant anymore, due the StartTime as unique identifier
      
      # Add columns for Comment TimeStamp and Operator for further Comment functions
      data$TimeStamp <- ""
      data$Operator <- ""
      data$Outlier <- "0"
      
      # Rename the columns
      names(data) <- c("Labels","StartTime","Comment","Intensity","Concentration","TimeStamp","Operator","Outlier")
      
      # Convert NA's in Comment column to empty characters
      data$Operator[!is.na(data$Comment)] <- myList$Input.Parameter$Operator
      data$TimeStamp[!is.na(data$Comment)] <- format(Sys.time(),"%Y-%m-%d")
      data$Comment[is.na(data$Comment)] <- ""
      
      # Collection in a list
      data.list[[myList[["Calibration"]][["Info"]][["Analytes"]][i]]] <- data
    }
    
  }else if(myList$Input.Parameter$System == "DMA80evo"){   # [CONVERTER: DMA80evo] ----
    # Merge:
    # "Labels","StartTime","Intensity","Concentration"
    
    data <- myList$Header %>% select(Nr,SampleName,StartTime,Remark) %>% # StartTime is available only in Header
      merge(.,myList$RawData$RawClean %>% select(Nr,SampleName,Height),by = c("Nr","SampleName")) %>% # Intensity is available only in Raw
      merge(.,myList$Concentration$Concentration %>% select(Nr,SampleName,Concentration)) %>%  # Concentration is available only in concentration
      select(-Nr) # Index is not relevant anymore, due the StartTime as unique identifier
    
    # Add columns for Comment TimeStamp and Operator for further Comment functions
    data$TimeStamp <- ""
    data$Operator <- ""
    data$Outlier <- "0"
    
    # Rename the columns
    names(data) <- c("Labels","StartTime","Comment","Intensity","Concentration","TimeStamp","Operator","Outlier")
    
    # Convert NA's in Comment column to empty characters
    data$Operator[!is.na(data$Comment)] <- myList$Input.Parameter$Operator
    data$TimeStamp[!is.na(data$Comment)] <- format(Sys.time(),"%Y-%m-%d")
    data$Comment[is.na(data$Comment)] <- ""
    
    # Collection in a list
    data.list[["Hg"]] <- data
    
  }else if(myList$Input.Parameter$System == "iTeva"){   # [CONVERTER: iTeva] ----
    
    
    for (i in 1:length(myList[["Calibration"]][["Info"]][["Analytes"]])) {
      
      # Merge:
      # "Labels","StartTime","Intensity","Concentration"
      
      # Raw concentration must be multiplied with the dilution factor in order to get not BG cleaned values (ONLY USED FOR QC)
      conc <- myList$Concentration$Concentration %>% select(Index,myList[["Calibration"]][["Info"]][["Analytes"]][i])
      conc[myList[["Calibration"]][["Info"]][["Analytes"]][i]] <- conc[myList[["Calibration"]][["Info"]][["Analytes"]][i]] * as.numeric(myList$Header$KorrFaktor)
      
      data <- myList$Header %>% select(Index,Probenname,Messzeit,Kommentar) %>% # StartTime is available only in Header
        merge(.,myList$Measured$Corrected.Means %>% select(Index,myList[["Calibration"]][["Info"]][["Analytes"]][i]),by = c("Index")) %>% # Intensity is available only in Raw
        merge(.,myList$Concentration$Concentration %>% select(Index,myList[["Calibration"]][["Info"]][["Analytes"]][i]),by = c("Index")) %>%  # Concentration is available only in concentration
        select(-Index) # Index is not relevant anymore, due the StartTime as unique identifier
      
      # Add columns for Comment TimeStamp and Operator for further Comment functions
      data$TimeStamp <- ""
      data$Operator <- ""
      data$Outlier <- "0"
      
      # Rename the columns
      names(data) <- c("Labels","StartTime","Comment","Intensity","Concentration","TimeStamp","Operator","Outlier")
      
      # Convert NA's in Comment column to empty characters
      data$Operator[!is.na(data$Comment)] <- myList$Input.Parameter$Operator
      data$TimeStamp[!is.na(data$Comment)] <- format(Sys.time(),"%Y-%m-%d")
      data$Comment[is.na(data$Comment)] <- ""
      
      # Collection in a list
      data.list[[myList[["Calibration"]][["Info"]][["Analytes"]][i]]] <- data
    }
    
  }else{
    return(NULL)
  }
  
  return(data.list)
}

# [WRITE data in QC files] ----
write.qc <- function(QCData,path,OverrideLine = F,KillOldFile = F){
  # CAUTION KillOld = TRUE parameter deletes the old QC file!!!!
  
  
  # Required!!!
  # Headlines must be given and must be identical to columns in path
  # QCData is a dataframe
  # All columns of QCData must be "character"
  
  
  # Read from probably existing data
  #_________________________________________________________
  
  # Function to (over)write QC-Values in the ControllChart
  if(file.exists(path) & KillOldFile == F){
    # Open existing file
    QCold <- read.QC(path)
  }else{ # falls Daten nicht vorhanden, anlegen einer neuen Datei
    QCold <- QCData
    write.csv(QCData, file = path,row.names=FALSE,na = "")
  }
  
  # Write new data
  #_________________________________________________________
  
  # Check for dublicates 
  if(nrow(QCold %>% filter(StartTime %in% QCData$StartTime)) > 0){ # Dublicate was found
    # Check for override flag
    if(OverrideLine == TRUE) { # if override flag is set, the old duplicate is removed
      QCold <- QCold %>% filter(!StartTime %in% QCData$StartTime) # Filter the old QC data with execption of dublicate
    }else {
      # When dublicates should not be overwritten, but other new data is additionally available
      newDataStartTime <- setdiff(QCData$StartTime,QCold$StartTime)
      QCData <- QCData %>% filter(StartTime %in% newDataStartTime)
      if (nrow(QCData) == 0) {
        # Abort the function and return FALSE when dublicate was found and an override is not allowed
        return(FALSE) 
      }
    }
  }
  
  QCtowrite <- rbind(QCold,QCData) # Binding the neu QC line to old data
  QCtowrite <- QCtowrite[order(QCtowrite$StartTime,decreasing = T),] # Sorting by StartTime
  write.csv(QCtowrite, file = path,row.names=FALSE,na = "") # whrite the new modified QC data
  
  # Return TRUE when successfully written data
  return(TRUE)
}

# [READ QC files] ----
read.QC <- function(path){
  # Open existing file
  QC <- read.csv2(path,header = T,sep = ",")
  # Read twice and fromat the columns in characters (the second read is nessecary to get the number of columns in the file)
  QC <- read.csv2(path,header = T,sep = ",",colClasses = rep("character",ncol(QC)))
  # Bugfix for older files
  
    if (is.null(QC[["Comment"]])) {
      if (nrow(QC) != 0) {
        QC$Comment <- ""
      }else{
        QC[["Comment"]] <- c()
      }
    }
    if (is.null(QC[["TimeStamp"]])) {
      if (nrow(QC) != 0) {
        QC$TimeStamp <- ""
      }else{
        QC[["TimeStamp"]] <- c()
      }
    }
    if (is.null(QC[["Operator"]])) {
      if (nrow(QC) != 0) {
        QC$Operator <- ""
      }else{
        QC[["Operator"]] <- c()
      }
    }
    if (is.null(QC[["Outlier"]])) {
      if (nrow(QC) != 0) {
        QC$Outlier <- "0"
      }else{
        QC[["Outlier"]] <- c()
      }
    }

  return(QC)
}

# [DELETE QC Points] ----
delete.QC <- function(path,StartTime){
  # function to delete a selected QC point
  
  # read QC file
  qc <- read.QC(path)
  # extract all values except the deleted one
  QCtowrite <- qc[!grepl(StartTime,qc$StartTime),]
  # Overwrite the QC file with updated values
  write.csv(QCtowrite, file = path,row.names=FALSE,na = "") # whrite the new modified QC data
  return(TRUE)
}


# [GRAPHICS] ----
  
myBlindwertkartenPlot <- function(plotData = plotData, BWKrit=NA,title = "Blindwertkarte", yLabel = "Intensität",xLabel = "Messzeitpunkt"){ # Blindwertkarte ----
  
  # Store the origin input data
  dfStore <- plotData
  
  # Remove NA's
  # plotData <- plotData %>% filter(!is.na(plotData$Concentration))
  
  # Bugfix for older QC files without comment column
  if (is.null(plotData[["Comment"]])) {
    plotData$Comment <- ""
  }
  if (is.null(plotData[["TimeStamp"]])) {
    plotData$TimeStamp <- ""
  }
  if (is.null(plotData[["Operator"]])) {
    plotData$Operator <- ""
  }
  if (is.null(plotData[["Outlier"]])) {
    plotData$Outlier <- "0"
  }
  
  if (nrow(plotData) == 0){
    # Creat an empty Plot if no data is available
    plotData[1,"Labels"] <- "No Data"
    plotData$StartTime <- format(Sys.time(),"%Y-%m-%d") %>% as.POSIXct()
    plotData$Concentration <- 0
    
    g <- ggplot(plotData,aes(StartTime, Concentration, label = "")) + 
      theme_minimal() +
      labs(y = yLabel,
           x = xLabel,
           title = title) +
      geom_text(na.rm =T,nudge_y = 1)
    
    return(g)
  }
  ### Convert formats for plot
  plotData$StartTime %<>% strptime(format ="%Y-%m-%d %H:%M:%S") %<>% as.POSIXct()
  plotData$Concentration %<>% as.numeric()
  # Exctract rows with comments
  logVec.comment <- plotData$Comment != ""
  # Generate new empty column called plotlabel to store the text for labeling within the plot
  plotData$plotlabel <- ""
  # Generate the label text only for rows with comment
  plotData[logVec.comment,"plotlabel"] <- paste(plotData[logVec.comment,"Labels"],dfStore[logVec.comment,"StartTime"],sep = "\n")
  
  # Generate the Plot
  ggplot(plotData,aes(StartTime, Concentration, label = plotlabel)) + 
    geom_point(na.rm = T) + 
    geom_line(na.rm = T) +
    geom_hline(yintercept = BWKrit,colour = "red",linetype="dashed",na.rm = TRUE) +
    #scale_y_continuous(expand = c(0, 0), limits = c(0,max(c(max(plotData$Value),BWKrit)*1.3))) +
    theme_minimal() +
    labs(y = yLabel,
         x = xLabel,
         title = title) +
    geom_text(na.rm =T,nudge_y = 1)
  
}

  
myZielwertkartenPlot <- function(plotData = plotData, Zielwert = 100, Unsicherheit = 26 ,title = title,yLabel = yLabel,xLabel = xLabel){ # Zielwertkarte ----
  
  # Store the origin input data
  dfStore <- plotData
  
  # Remove NA's
  # plotData <- plotData %>% filter(!is.na(plotData$Concentration))
  
  # Bugfix for older QC files without comment column
  if (is.null(plotData[["Comment"]])) {
    plotData$Comment <- ""
  }
  if (is.null(plotData[["TimeStamp"]])) {
    plotData$TimeStamp <- ""
  }
  if (is.null(plotData[["Operator"]])) {
    plotData$Operator <- ""
  }
  if (is.null(plotData[["Outlier"]])) {
    plotData$Outlier <- "0"
  }
  
  if (nrow(plotData) == 0){
    # Creat an empty Plot if no data is available
    plotData[1,"Labels"] <- "No Data"
    plotData$StartTime <- format(Sys.time(),"%Y-%m-%d") %>% as.POSIXct()
    plotData$WFR <- 0
    
    g <- ggplot(plotData,aes(StartTime, WFR, label = "")) + 
      theme_minimal() +
      labs(y = yLabel, x = xLabel, title = title) +
      geom_text(na.rm=T,nudge_y = 10)
    
    return(g)
  }
  
  # Define the thresholds
  OKG <- Zielwert + Unsicherheit
  UKG <- Zielwert - Unsicherheit
  
  ### Convert formats for plot
  plotData$StartTime %<>% strptime(format ="%Y-%m-%d %H:%M:%S") %<>% as.POSIXct()
  plotData$Concentration %<>% as.numeric()
  plotData$WFR %<>% as.numeric()
  plotData$Defined %<>% as.numeric()
  
  # Exctract rows with comments
  logVec.comment <- plotData$Comment != ""
  # Generate new empty column called plotlabel to store the text for labeling within the plot
  plotData$plotlabel <- ""
  # Generate the label text only for rows with comment
  plotData[logVec.comment,"plotlabel"] <- paste(plotData[logVec.comment,"Labels"],dfStore[logVec.comment,"StartTime"],sep = "\n")
  
  # Generate the Plot
  ggplot(plotData,aes(StartTime, WFR, label = plotlabel)) + 
    geom_point(na.rm = T) + 
    geom_line(na.rm = T) +
    geom_hline(yintercept = OKG,colour = "red",linetype="dashed",na.rm = TRUE)+
    geom_hline(yintercept = UKG,colour = "red",linetype="dashed",na.rm = TRUE)+
    geom_hline(yintercept = Zielwert,colour = "black",na.rm = TRUE)+
    theme_minimal() +
    labs(y = yLabel, x = xLabel, title = title) +
    geom_text(na.rm=T,nudge_y = 10)
}

myRegelkartenPlot <- function(x, y, title, yLabel, xLabel){ # Zielwertkarte ----
  # A Plot  for general use!
  #------------------------#
  
  plotData <- data.frame("xVal" = x,
                         "yVal" = y,
                         stringsAsFactors = F)
  # x and y must be numeric!
  
  # Define the thresholds
  OWG <- mean(y) + 2*sd(y)
  UWG <- mean(y) - 2*sd(y)
  
  OKG <- mean(y) + 3*sd(y)
  UKG <- mean(y) - 3*sd(y)
  
  
  # Generate the Plot
  ggplot(plotData,aes(xVal, yVal)) + 
    geom_point(na.rm = T) + 
    geom_line(na.rm = T) +
    geom_hline(yintercept = OWG,colour = "orange",linetype="dashed",na.rm = TRUE)+
    geom_hline(yintercept = UWG,colour = "orange",linetype="dashed",na.rm = TRUE)+
    geom_hline(yintercept = OKG,colour = "red",linetype="dashed",na.rm = TRUE)+
    geom_hline(yintercept = UKG,colour = "red",linetype="dashed",na.rm = TRUE)+
    geom_hline(yintercept = mean(y),colour = "black",na.rm = TRUE)+
    theme_minimal() +
    labs(y = yLabel, x = xLabel, title = title) 
}

qc.spike <- function(conc.org,conc.spk,conc.def){
  # Function o calculate the accuracy in spiked real samples
  #
  # For correct treatment:
  # The vector conc.org can be of length 1, or
  # the length of both vectors has to be the same.
  # For special pairing, conc.org and conc.spk must be named vectors to concatenate corresponding pairs
  
  # Check for length of vectors and select the case
  conc.org.Pair <- conc.org
  if (length(conc.org) > 1 && length(conc.org) != length(conc.spk)) {
    # Error handling
    if (length(conc.org) > length(conc.spk)) {
      return(list("conc.org" = conc.org.Pair,
                  "conc.spk" = conc.spk,
                  "Defined" = conc.def,
                  "Concentration" = NA,
                  "WFR" = NA))
    }
    # Pairing in loop
    conc.org.Pair <- c()
    for (i in 1:length(conc.spk)) {
      conc.org.Pair <-c(conc.org.Pair,
                        conc.org[str_detect(names(conc.spk)[i],paste0("^",names(conc.org)))]
                        )
    }
  }
  
  WFR <- (conc.spk - conc.org.Pair)/conc.def*100
  return(list("conc.org" = conc.org.Pair,
              "conc.spk" = conc.spk,
              "Defined" = conc.def,
              "Concentration" = (conc.spk - conc.org.Pair),
              "WFR" = WFR))
}

comment.QC <- function(path,StartTime,str.comment,TimeStamp,Operator){
  # function to add a comment to a selected QC point
  
  # read the destinated QC file
  qc <- read.QC(path)
  
  # proof if a comment column is available in read QC-File and set one if not
  # (older QC files generated prior this function)
  if (is.null(qc[["Comment"]])) {
    qc$Comment <- ""
  }
  if (is.null(qc[["TimeStamp"]])) {
    qc$TimeStamp <- ""
  }
  if (is.null(qc[["Operator"]])) {
    qc$Operator <- ""
  }
  
  
  # Filtern der zu kommentierenden Daten
  qc[str_detect(pattern = StartTime,string = qc$StartTime),"Comment"] <- str.comment
  qc[str_detect(pattern = StartTime,string = qc$StartTime),"TimeStamp"] <- TimeStamp
  qc[str_detect(pattern = StartTime,string = qc$StartTime),"Operator"] <- Operator
  
  # Überschreiben der QC Daten
  # check for changes before write csv
  # Proof of CheckSum of the stored csv and the new one)
  #if(all(equals(md5(as.character(read.QC(QCpath))),md5(as.character(qc))))){return(FALSE)}
  
  write.csv(qc, file = path,row.names=FALSE,na = "") # whrite the new modified QC data
  return(TRUE)
}

setOutliers <- function(path,Outlier){
  # function to set an outlier to a selected QC point
  
  # read the destinated QC file
  qc <- read.QC(path)
  
  # Reset prior settings of outlier.
  #if (is.null(qc[["Operator"]])) {
  qc$Outlier <- "0"
  qc$Outlier[Outlier] <- "1"
  #}
  
  # Set the new Outlier selection
  #qc$ <- as.character(as.numeric(Outlier))
  
  # Store in QC file
  write.csv(qc, file = path,row.names=FALSE,na = "") # whrite the new modified QC data
  return(TRUE)
}


read.QC.Archive <- function(path){
  # Function to read and output the QC archiev index file as data.frame 
  QC <- read.csv2(path,header = T,sep = ",",stringsAsFactors = F)
  return(QC)
}

get.QC.Archiev <- function(path.QCIndex,QC.Filename){
  # function to extract the names of linked QC archiev files
  df <- read.QC.Archiev(path.QCIndex)
  out <- df[[QC.Filename]]
  out <- c(QC.Filename,out[!is.na(out)])
  return(out)
}
